### ISSUE TITLE
Double-bolded icons

### ISSUE THREAD

**Issue by laktiv** [chrisgurney/obsidian-note-toolbar#162]
**Description of the bug**
Icons in callout's toolbar have doubled "stroke-width" attribute which makes icon very bold.

This snipped fix it:
```css
.cm-callout [data-callout="note-toolbar"] .cm-iconize-icon svg svg[stroke-width='16px'] {
  stroke-width: 2;
} 	/*/ Fix very bold icons */
```

**Expected behavior**
Regular icon's bold.

**Screenshots (if you think it will help)**
Compared to toolbar Fixed top (above):
![](https://i.imgur.com/7oJAtd0.png)

Callout in note:
![](https://i.imgur.com/AS1UnnX.png) 
![](https://i.imgur.com/bWBr3Z0.png)

**Desktop environment:**
 - OS: Windows 11
 - Obsidian version: 1.7.4
 - Note Toolbar version: 1.14.3

**Comment by chrisgurney** [comment]
@laktiv Thank you! I noticed this but wasn't quite sure what was going on here. I'll patch in your fix for now. Appreciate it!

**Comment by chrisgurney** [comment]
@laktiv Fixed in [1.14.4](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.14.4). Thanks again!

**Comment by laktiv** [comment]
@chrisgurney sure, but later.
I'm checking other noted bugs and want to publish them. One already fixed not in beta, checking others.

**Comment by laktiv** [comment]
Not worked with callouts. Example callout in note:
```md
> [!note-toolbar|even|border]
> ```dataview
> LIST WHERE file.starred SORT file.name
> ```
```

Fix that solves the issue:
```css
[data-callout="note-toolbar"] svg[stroke-width='16px'] {
	stroke-width: 2;
}
```

**Comment by chrisgurney** [comment]
@laktiv Hmm, I gave that a go with my bookmarks and I don't have any icons in them. I can't seem to add any icons either, since `:` is invalid in filenames.

Can you give me more context? A screenshot and/or what the name of the bookmarked files are?

Hopefully we can scope this fix to Iconize's icons, if that's indeed the issue. But perhaps it's a bigger issue than that.

**Comment by chrisgurney** [comment]
Just read a comment that made me think that I didn't try adding icons to the bookmark names/aliases rather than the file names. I'll give that a go when I get a chance.

**Comment by chrisgurney** [comment]
@laktiv I still can't reproduce this -- icons aren't showing up on my list.

I made a bookmark with the name `:home: Page Name` but icons don't show up in that Dataview query. Interestingly, only two of my four bookmarks appear in the list using that query... not sure why.

**Comment by chrisgurney** [comment]
Ahh, this is what I needed to do: https://florianwoelki.github.io/obsidian-iconize/files-and-folders/icon-before-file-or-folder.html

Reproduced:
![CleanShot 2024-11-04 at 07 03 40@2x](https://github.com/user-attachments/assets/6656e6c8-8d67-4b63-8d63-8789e8291157)

**Comment by chrisgurney** [comment]
OK, I have a fix committed. Will be in the next beta. Thanks for your patience @laktiv !

**Comment by chrisgurney** [comment]
@laktiv The fix is in the latest beta. Please give it a go when you get a chance, and let me know if it looks OK on your end.

**Comment by laktiv** [comment]
Hi Chris,
Looks like the issue is still there. 
![image](https://github.com/user-attachments/assets/05e473d1-0cf3-48f9-a792-3d82e10d3076)
I've disabled all snippets, and plugins with possible additional style, reinstalled plugin thru Brat and close/open the Obsidian before taking screenshot. Icon [:LiObsidian:], Callout panel in text. Same panel using not like callout works fine.

PS: Thank you for fixing. If you have more important stuff to do, please take note that this issue is not making life hard. Unlike JsEngine and Templater... 🤬

**Comment by chrisgurney** [comment]
@laktiv Okay thanks, I'll take a look at that icon. It's possible the CSS override is too specific.

**Comment by chrisgurney** [comment]
@laktiv Any idea what adds the `:LiObsidian:` icon? I don't have it when I try to use it with Iconize. Perhaps one of your plugins adds it? If you're not sure, I might have to search through the code used by the plugins you have installed, in which case I'll need a list.

**Comment by laktiv** [comment]
Hi @chrisgurney 
I've reopened this script where all icons are listed and check the source code of this specific icon.
I looks like this stroke-width 4 is a part of svg code. Why it looks normal everywhere besides note panel I don't know, can't figure it out. 
But this case is obviously my fault, not your. I'm very sorry that took your time at this. 

![image](https://github.com/user-attachments/assets/7c5584fd-18e2-4327-b01a-891ea7754790)
